[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'rm -rf node_modules',
  'rm -rf package-lock.json',
  'npm install --force --include=optional'
]

[phases.build]
cmds = [
  'npm run railway:build'
]

[start]
cmd = 'npm start'